### ISSUE TITLE
ขอคำปรึกษาเรื่องแบบของ Baijam ครับ

### ISSUE THREAD

**Issue by parin-rungpattarathakun** [cadsondemak/Bai-Jamjuree#1]
1. แบบตัวอักษรทั้งหมดที่ปรับครับ
<img width="709" alt="preview-lightbox-screen shot 2561-01-22 at 4 56 17 pm" src="https://user-images.githubusercontent.com/35288945/36087713-5e474524-1006-11e8-8591-90899230e654.png">

2.  ตามแบบเดิมโครงสร้าง C O Q G ดูเอียงผิดจากตัวอื่นๆ ผมควรปรับไหมครับ หรือคงแบบไว้อย่างเดิม
<img width="860" alt="preview-lightbox-screen shot 2561-01-22 at 5 21 24 pm" src="https://user-images.githubusercontent.com/35288945/36087746-77920762-1006-11e8-9f26-45b15a0a648e.png">

3. apex ของ A W V M ควรเก็บหรือสามารถเอาออกได้ครับ เพราะผมเห็นว่าถึงแม้ w จะใช้โครงสร้างร่วมกับตัว พ แต่เมื่อใช้กับภาษาอังกฤษด้วยกันเองแล้วดูแปลกตา
<img width="730" alt="preview-lightbox-screen shot 2561-01-22 at 5 20 05 pm" src="https://user-images.githubusercontent.com/35288945/36087757-841789f8-1006-11e8-82e0-94825f738a0d.png">
https://guides.github.com/features/mastering-markdown/

**Comment by suppakit-** [comment]
2. โดยเจตนาของผู้ออกแบบ ได้นำหลังคาของตัวอักษรมีปาก(ชุด ก) มาเป็นเงื่อนไขในการออกแบบส่วนโค้งของตัวอักษรอื่นๆ เช่นในตัวภาษาไทยก็จะมี ค ฉ ด ล ส อ และได้นำมาใส่ในส่วนโค้งของตัวอักษรภาษาอังกฤษด้วยเช่นเดียวกัน แต่ปัญหาที่เกิดขึ้น คือส่วนโค้งนี้ ไม่ถูกนำไปใส่ครบในตัวอักษรภาษาอังกฤษที่ต้องเป็นโค้งแบบเดียวกัน เช่น S, b(โค้งล่างขวา), g(โค้ง tail), p(โค้งล่างขวา), q(โค้งบนซ้าย), s เป็นต้น กรณีนี้เพื่อเป็นการเคารพเจตนาของผู้ออกแบบจึงควรเก็บรายละเอียดตรงส่วนนี้ไว้ โดยอาจจะลดทอนการโค้ง(เพื่อให้ความเฉียงน้อยลง ซึ่งดูได้จากโค้งของตัวพิมพ์เล็กที่มีการเฉียงที่น้อยกว่า) รวมถึงนำส่วนโค้งนี้ไปใส่เพิ่มเติมในส่วนที่ขาด  (เมื่อลดส่วนโค้งที่มากให้น้อยลงแล้ว เมื่อเพิ่มส่วนที่ขาดก็จะเป็นการเพิ่มขึ้นเพียงนิดเดียวซึ่งทำให้แบบไม่เปลี่ยนไปจากเดิมมากเกินไป) เพื่อปรับให้ฟอนต์ทั้งชุดมีความกลมกลืนและเข้ากัน โดยไม่รู้สึกแปลกตาหรือเปลี่ยนแบบจากเดิม

3. เช่นเดียวกับข้อ 2. คือควรเก็บเจตนาของแบบไว้ เพียงแต่อาจจะลดความแรงของ apex (ปรับส่วนด้านโค้งให้โค้งน้อยลง) เพื่อให้ทุกตัวตัวอักษรที่มีส่วนนี้ไม่ดูโดดออกไปจากภาพรวมของตัวอักษรทั้งชุด

ป.ล. ทั้งหมดเป็นเพียงข้อเสนอแนะและความเห็น ทั้งนี้ขึ้นอยู่กับดุลพินิจของผู้ได้รับมอบหมายและหัวหน้าทีมของผู้ดูแลโปรเจ็ค Google DEPA

รูปประกอบเพื่อใช้เป็นตัวอย่างในการลด Apex ของข้อ 3.

**Comment by cadsondemakoffice** [comment]
ละตินไม่ต้องพยายามมากเกินไปนะครับ พยายามอยู่บนความ practical มากกว่าต้นแบบ ตามที่พี่สมิธแนะไป คือควรเก็บเจตนาของแบบไว้ เพียงแต่อาจจะลดความแรง ซึ่งในที่นี้คือที่ผมหมายถึงว่ามันควร practical ใช้งานได้จริงมากกว่าที่เป็นอยู่นี้ ส่วนภาษาไทยก็แก้ดรออิ้งปรับความกว้างในบางตัวที่ต้องการ เก็บเจตนาเดิมก็น่าจะพอไปได้อยู่แล้วสำหรับตัวนี้

**Comment by AnuthinWongsunkakon** [comment]
ครับ ตามนั้นครับ อยากให้มันดูแล้วใช้งานได้จริงมากกว่าควอลิตี้ของการตกแต่งครับ เจตนาแบบมันมีสองขั้น ขั้นโครงสร้าง ซึ่งเป็นขั้นที่เปลี่ยนไม่ได้ หรือปรับก็คงได้ไม่เยอะ และขั้นตกแต่ง อันนี้ก็จะปรับเปลี่ยนได้เยอะกว่าตามข้อแม้และปัญหาที่จะไปเจอ อยากให้มันดูใช้งานได้จริง ทั้งชุดนี้ปัญหาใหญ่น่าจะอยู่ที่สัดส่วนมากกว่าอย่างอื่นครับ ละตินจะหนักหน่อย

**Comment by AnuthinWongsunkakon** [comment]
ผมส่งไฟล์ให้พี่เช่ไปแล้วครับ น่าจะช่วยเรื่องละตินได้ประมาณนึง

**Comment by parin-rungpattarathakun** [comment]
ขอบคุณมากๆครับ @suppakit-  @cadsondemak/owners  @AnuthinWongsunkakon

**Comment by AnuthinWongsunkakon** [comment]
มีสกรีนช็อตไหมครับ ได้ใช้อะไรจาก Myers Sans บ้างไหม Please give a follow up result on the application and implementation from the FOG file I gave you.

**Comment by davelab6** [comment]
The v and w have curved apexes which is a 'decorative' feature, and while this appears in some of the Thai apexes, not all Thai apexes use this, which is sensitive and correct to use them only sparingly; perhaps at the top of the middle w and the bottom of v only? :)

**Comment by davelab6** [comment]
The J can be more narrow overall. 

Generally I think the Latin could be more DIN than Microgramma

**Comment by AnuthinWongsunkakon** [comment]
@parin-rungpattarathakun Could you please put up the latest version of the screenshot?

**Comment by parin-rungpattarathakun** [comment]
this is last version for now.
<img width="932" alt="screen shot 2561-03-14 at 11 59 54 am" src="https://user-images.githubusercontent.com/35288945/37384082-433d579c-277f-11e8-9d67-439c1558d20b.png">

**Comment by Thanarat-Vachiruckul** [comment]
My opinion, I think the latin should be more practical. C, G, O and Q with decorative curve make them look oblique to me while the rest of them look normal upright. this curve work just fine with Thai alphabets but when applied them to latin it don't feel right.

โค้งตาม Concept ที่ใส่มาในตัว C G O Q S D และ U ทำให้ตัวอักษรดูเอียงครับ (ในขณะที่ตัวภาษาไทยไม่ค่อยเกิดปัญหานี้) น่าจะต้องลองปรับลดเรื่อง Concept ลงให้มันใช้งานได้จริงมากขึ้น สำหรับเรื่องที่มาของแบบ detail ที่เป็นเอกลักษณ์อันนี้ผมเข้าใจดีครับ ในกรณีที่ใช้งานร่วมกันทั้งสองภาษาก็จะมีความเชื่อมโยงกันของ concept แต่หากในกรณีที่ผู้ใช้งานนำลาตินไปใช้อย่างเดียวและไม่มีความเชื่อมโยงกันของตัวภาษาไทยแล้วก็จะเห็นได้ว่าตัวอักษรที่กล่าวถึงข้างต้นเมื่อใช้งานร่วมกันก็จะดูแปลกขึ้นมาทันที

**Comment by davelab6** [comment]
I agree

**Comment by kanorider** [comment]
Uppercase: 
P B R 
ดูใหญ่เกินไปซึ่งส่งอาจจะผลให้เจตนาของแบบเปลี่ยน
X Y เส้นเฉียงบางไป 
N stem หน้าหลังสามารถบางลงได้นิดนึงเพื่อลวงตา
K เปลี่ยนเยอะไปเจตนาเปลี่ยน
P อ้วนไป
W ผอมไปสามารทำให้อ้วนขึ้นได้ด้วยการดึงขาด้านซ้ายและออกไปอีกก็จะช่วยได้
C อ้วนไป 
G ผอมไปเมื่อเทียบกับ O

Lowercase:
a stem ด้านหลังหนาไปบางลงได้อีก แล้วดูอ้วนไป
u ดูอ้วนไป โดยปกติแล้ว u ควรจะผอมกว่า n เล็กน้อยเพราะเป็นทรงเปิด 
m สามารถอ้วนขึ้นได้มากกว่านี้เพื่อให้เวลาดูภาพรวมจะมีพื้นที่สี่ขาวที่ดูสม่ำเสมอมากขึ้น
c อ้วนไป

**Comment by AnuthinWongsunkakon** [comment]
There is no reason to support the off balance Oo shape in this set. I could not see anything that could back this up. The original design was using this odd shape to make believe that the design is special. It did not work to begin with so why bother to keep a feature that fail in this version. 

Please readjust all the O shape related forms back to center balance.

**Comment by AnuthinWongsunkakon** [comment]
1. หางขมวดของ ฬ จถฬา เล็กเกินไป
2. ปากของเซ็ต ก ไก่ ทั้งหมดให้ชันขึ้นกว่านี้ แล้วก็ชานหน้าในหมวด ก ไก่ทั้งหมด เข้ามาลึกทางขวาได้มากกว่านี้ แล้วไปเพิ่มความกว้างของสิธเพื่อชดเชยแทน
3. ตัวอักษรทุกตัวที่มีเชปเต้าหู้ สี่เหลี่ยมขบอมน ทำให้บาลานซ์ให้หมด อย่าปล่อยให้เอียงแบบนี้ ตามที่พี่อู๋ @Thanarat-Vachiruckul ทักมา มันดูล้ม
4. จุดตัดของตัวที่มีหางทั้งหมดดูหนามากแล้วประกอบกับมุมโค้งด้านขวาบนของตัวอักษรอาทิ ส ศ ฮ เจอหางเข้าไปอีก กลายเป็นเชิดขึ้นไปหมด ถ้าปรับให้มุมโค้งของตัวอักษรไม่เลิกขึ้นไป ทำให้ทั้งสองมุมโค้งเท่ากันปัญหานี้ก็จะหายไปด้วย

**Comment by AnuthinWongsunkakon** [comment]
<img width="932" alt="37384082-433d579c-277f-11e8-9d67-439c1558d20b" src="https://user-images.githubusercontent.com/36420640/37437118-0bc54bf4-281e-11e8-9e4f-e5504d649df7.png">

**Comment by parin-rungpattarathakun** [comment]
Thank you for all comment, I’ll improve this.

**Comment by AnuthinWongsunkakon** [comment]
คิดว่า  @parin-rungpattarathakun  น่าจะดูไฟล์ .fog ที่ผมแนะนำไปแล้วเอาความ balance แบบนั้นมาใช้ให้มากกว่านี้ จะช่วยทำให้มันหายยวบๆละลายๆได้นะครับ ส่วนภาษาไทยลองดู นพพร ของ อาจารย์มานพ (ที่ดีบี เอามาทำเป็น ประดิษฐ)
![img_20170818_210704](https://user-images.githubusercontent.com/36420640/37476371-92f23a04-28a7-11e8-8206-41dd62ae4db2.jpg)

**Comment by kanorider** [comment]
เพิ่มเติมในส่วนขอภาษาไทยนะครับ
ฎ ฏ หัวขมวดด้านล่างดูบางไปสามารถทำให้หนาขึ้นได้อีกนิดนึงครับ
ฐ ส่วนด้านล่างบางไปสามารถทำให้หนาขึ้นได้อีกครับ
ฒ มวลด้านซ้ายดูแน่นมากสามารถช่วยลดมวลตรงนั้นได้ด้วยการขยับเส้นตั้งตรงกลางมาด้านขวาอีกก็จะช่วยได้ครับ
ย เส้นนอนตรงกลางดูสั้นไปสามารถทำให้ยาวขึ้นได้อีก และยกขึ้นอีกครับตอนนี้มันดูต่ำไปครับ
ะ ใหญ่เกินไปครับ

**Comment by parin-rungpattarathakun** [comment]
ผมจะรีบปรับแล้วมาอัพเดตนะครับ

**Comment by parin-rungpattarathakun** [comment]
เปรียบเทียบแบบก่อน และหลังปรับครับ

แบบเดิม
 <img width="932" alt="screen shot 2561-03-14 at 11 59 54 am" src="https://user-images.githubusercontent.com/35288945/37638220-4edd5a16-2c3e-11e8-87c7-8533c4147e70.png">
แบบหลังปรับแล้ว
<img width="1279" alt="screen shot 2561-03-20 at 12 52 56 pm" src="https://user-images.githubusercontent.com/35288945/37638134-dfbdbf5e-2c3d-11e8-972d-23819e53367e.png">

**Comment by AnuthinWongsunkakon** [comment]
First impression....I think 

- b c d e g h m n o p q r s u y are a bit too narrow. The Uppercases are not that narrow. 
- g is looking funny. I think you have the overshoot lifted too high from the baseline.

More later.
