### ISSUE TITLE
การปรับแบบภาษาไืทย และละติน

### ISSUE THREAD

**Issue by parin-rungpattarathakun** [cadsondemak/Bai-Jamjuree#6]
เพิ่มเส้นตรงบริเวณส่วนโค้งของ ข ฃ และ ต เพื่อความเข้ากันของแบบมากขึ้น
<img width="769" alt="screen shot 2561-06-05 at 3 09 10 pm" src="https://user-images.githubusercontent.com/35288945/40963533-0d73c534-68d3-11e8-9c78-70725e6daf26.png">

ปรับหัวของ ด ต ไปทางด้านซ้ายมากขึ้นตามธรรมชาติของการเขียน 
<img width="575" alt="screen shot 2561-06-05 at 3 18 05 pm" src="https://user-images.githubusercontent.com/35288945/40963831-b356d7f2-68d3-11e8-82d0-d606fe3810dc.png">

ปรับขาสองข้างของ W ออกเพื่อให้ negative ด้านในสมดุลมากขึ้น
<img width="416" alt="screen shot 2561-06-05 at 3 18 13 pm" src="https://user-images.githubusercontent.com/35288945/40963835-b7846808-68d3-11e8-81cb-c9f1aae83315.png">

**Comment by siringunkloy** [comment]
สามารถใช้ประโยชน์จากส่วนคอของ ข และ ฃ ได้มากกว่านี้ อาจทำได้โดยการเพิ่มองศาในการหัก โดยมุ่งไปที่การทำให้ส่วนโค้งชั้นสองของหัวหุบงอเข้าไปในลำตัว อันจะช่วยลดพื้นที่ด้านข้างตัวอักษรด้านซ้ายไม่ให้เหลือเยอะจนเกินไป
